In [3]:
import torch as th
import torch.nn.functional as F
from func import qtd_loss, c51_loss
import gymnasium
import numpy as np

In [2]:
a = th.rand((1,)).expand((16,))
a

tensor([0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017,
        0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017])

In [3]:
x = th.rand((3, 2)).unsqueeze(2)
x.shape

torch.Size([3, 2, 1])

In [4]:
y = th.rand((3, 2, 2)) + 0.5
print(y)
F.huber_loss(y, th.zeros_like(y), reduction='none')

tensor([[[0.6624, 1.4965],
         [1.1151, 0.5849]],

        [[1.0970, 1.1830],
         [1.0751, 1.3220]],

        [[0.6376, 0.6500],
         [0.9179, 1.2292]]])


tensor([[[0.2194, 0.9965],
         [0.6151, 0.1710]],

        [[0.5970, 0.6830],
         [0.5751, 0.8220]],

        [[0.2033, 0.2112],
         [0.4213, 0.7292]]])

In [5]:
pre = th.tensor([[1, 2]])
target = th.tensor([2, 3])

In [6]:
reward = th.tensor([[0.0312, 0.0938, 0.1562, 0.2188, 0.2812, 0.3438, 0.4062, 0.4688, 0.5312,0.5938, 0.6562, 0.7188, 0.7812, 0.8438, 0.9062, 0.9688]]).expand(32, 16)

In [7]:
tau = th.tensor([i/32 for i in range(1, 32, 2)])
s1 = th.tensor([[0.0312, 0.0938, 0.1562, 0.2188, 0.2812, 0.3438, 0.4062, 0.4688, 0.5312, 0.5938, 0.6562, 0.7188, 0.7812, 0.8438, 0.9062, 0.9688]])
s2 = th.tensor([[0.1546, 0.2434, 0.3010, 0.3466, 0.3849, 0.4200, 0.4527, 0.4844, 0.5156, 0.5473, 0.5800, 0.6151, 0.6534, 0.6990, 0.7566, 0.8454]])

qtd_loss(s1, s1, tau), qtd_loss(s2, s1, tau)

(tensor(21.2504), tensor(22.8334))

In [8]:
reward = th.rand((32, 1)).expand(-1, 16)

In [9]:
th.empty(3, dtype=th.long).random_(5)

tensor([1, 1, 0])

In [10]:
F.cross_entropy(th.tensor([0.5, 0.5]), th.tensor([0.5, 0.5]), reduction='none')

tensor(0.6931)

In [46]:
a = th.tensor([[0.0563, 0.0656, 0.0668, 0.0636, 0.0552, 0.0606, 0.0683, 0.0576,
               0.0682, 0.0678, 0.0585, 0.0589, .0658, 0.0662, 0.0677, 0.0527]])
b = th.tensor([[0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625,
              0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625]])


th.sum(b * th.log(b)), th.sum(b * th.log(a))
# c51_loss(a, b), c51_loss(b, b)

(tensor(-2.7726), tensor(-2.7762))

In [40]:
a = th.arange(0, 6).view(2, 3)
b = th.arange(0, 6).view(2, 3)
a * b

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [17]:
th.cos(th.arange(0, 16) * th.tensor([[1.0, 1.0], [2.0, 2.0]]).unsqueeze(-1) * th.pi)

tensor([[[ 1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
           1., -1.],
         [ 1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
           1., -1.]],

        [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
           1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
           1.,  1.]]])

In [1]:
th.tensor([1, 2]).unsqueeze(-1)

NameError: name 'th' is not defined

In [5]:
th.argmax(th.tensor([2, 1, 4])).item()

2

In [8]:
env = gymnasium.make("MountainCar-v0")

obs, _ = env.reset()
obs

array([-0.5069796,  0.       ], dtype=float32)

In [19]:
a = np.array([1.0])
b = np.array([2, 3], dtype=np.float32)
th.from_numpy(np.concatenate([a, b]))

tensor([1., 2., 3.], dtype=torch.float64)

In [10]:
observation = np.array([1.0, 2.0])
a = 3
th.from_numpy(np.concatenate([observation, np.array([a], dtype=np.float32)])).unsqueeze(0)

tensor([[1., 2., 3.]], dtype=torch.float64)

In [49]:
np.random.randint(0, 3)

0