In [24]:
import torch as th
import torch.nn.functional as F
from func import qtd_loss

In [3]:
a = th.rand((1,)).expand((16,))
a

tensor([0.5984, 0.5984, 0.5984, 0.5984, 0.5984, 0.5984, 0.5984, 0.5984, 0.5984,
        0.5984, 0.5984, 0.5984, 0.5984, 0.5984, 0.5984, 0.5984])

In [4]:
x = th.rand((3, 2)).unsqueeze(2)
x.shape

torch.Size([3, 2, 1])

In [13]:
y = th.rand((3, 2, 2)) + 0.5
print(y)
F.huber_loss(y, th.zeros_like(y), reduction='none')

tensor([[[1.4507, 0.8740],
         [1.4896, 0.9463]],

        [[0.6195, 1.1873],
         [1.0408, 1.0343]],

        [[0.8719, 1.4854],
         [0.5102, 0.7439]]])


tensor([[[0.9507, 0.3820],
         [0.9896, 0.4478]],

        [[0.1919, 0.6873],
         [0.5408, 0.5343]],

        [[0.3801, 0.9854],
         [0.1302, 0.2767]]])

In [ ]:
pre = th.tensor([[1, 2]])
target = th.tensor([2, 3])

In [14]:
reward = th.tensor([[0.0312, 0.0938, 0.1562, 0.2188, 0.2812, 0.3438, 0.4062, 0.4688, 0.5312,0.5938, 0.6562, 0.7188, 0.7812, 0.8438, 0.9062, 0.9688]]).expand(32, 16)

In [26]:
tau = th.tensor([i/32 for i in range(1, 32, 2)])
s1 = th.tensor([[0.0312, 0.0938, 0.1562, 0.2188, 0.2812, 0.3438, 0.4062, 0.4688, 0.5312, 0.5938, 0.6562, 0.7188, 0.7812, 0.8438, 0.9062, 0.9688]])
s2 = th.tensor([[0.1546, 0.2434, 0.3010, 0.3466, 0.3849, 0.4200, 0.4527, 0.4844, 0.5156, 0.5473, 0.5800, 0.6151, 0.6534, 0.6990, 0.7566, 0.8454]])

qtd_loss(s1, s1, tau), qtd_loss(s2, s1, tau)

(tensor(4.2667), tensor(3.7943))

In [18]:
reward = th.rand((32, 1)).expand(-1, 16)